server:
  port: 8082

spring:
  application:
    name: blog-service
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
      config:
        server-addr: nacos:8848
        file-extension: yaml
  datasource:
    url: jdbc:postgresql://postgres:5432/blog_db
    username: blog_user
    password: blog_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: redis
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    port: 8082
  info:
    env:
      enabled: true

# 日志配置
logging:
  level:
    root: INFO
    com.blog: DEBUG
    org.springframework.data: INFO

# 文章配置
blog:
  article:
    page-size: 10
    summary-length: 200
    cache-ttl: 3600