server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 博客服务路由
        - id: blog-service
          uri: lb://blog-service
          predicates:
            - Path=/api/blog/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.key-resolver: '#{@userKeyResolver}'
        # 用户服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        # 管理服务路由
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=1
        # 监控服务路由
        - id: monitor-service
          uri: lb://monitor-service
          predicates:
            - Path=/api/monitor/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: blog-dev
  redis:
    host: localhost
    port: 6379
    password: ''

# 网关全局配置
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG

# JWT配置
jwt:
  secret: 8e3b9d7f6a1c4e2d9b7f3a5c8e6d2b4f7a9d3c5e8b6d2f4a7c9e3b5d8f6a1c4e