server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
      config:
        server-addr: nacos:8848
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - JwtAuth=exclude=/api/auth/login,/api/auth/register
            - RequestRateLimiter=100,100
        
        - id: blog-service
          uri: lb://blog-service
          predicates:
            - Path=/api/articles/**,/api/categories/**,/api/tags/**,/api/comments/**,/api/tracking/**
          filters:
            - StripPrefix=1
            - JwtAuth=exclude=/api/articles/**,/api/categories/**,/api/tags/**,/api/comments/**
            - RequestRateLimiter=200,200

        - id: monitor-service
          uri: lb://monitor-service
          predicates:
            - Path=/api/monitor/**
          filters:
            - StripPrefix=1
            - JwtAuth=exclude=none
            - RequestRateLimiter=50,50

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=1
            - JwtAuth=exclude=/api/admin/auth/login
            - RequestRateLimiter=50,50
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
  redis:
    host: redis
    port: 6379

# JWT配置
jwt:
  secret: ${JWT_SECRET:your-secret-key-for-jwt-token}
  expiration: 3600000

# Actuator配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    port: 8080
  info:
    env:
      enabled: true

# 日志配置
logging:
  level:
    root: INFO
    com.blog: DEBUG
    org.springframework.cloud.gateway: TRACE